# Process config example for dataset

# global parameters
project_name: 'sharegpt_zh'
dataset_path: './input/sharegpt_zh.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: './output/analysis/sharegpt_zh/sharegpt_zh.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'zh'
  - normal_filter:
  - token_num_filter:
     hf_tokenizer: "baichuan-inc/Baichuan2-7B-Base"
     min_num: 1000
     max_num: 4000